/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CBox {
    }
    interface HBox {
        "bottom": boolean;
        "fill": boolean;
        "spread": boolean;
        "top": boolean;
        "wrap": boolean;
    }
    interface VBox {
    }
}
declare global {
    interface HTMLCBoxElement extends Components.CBox, HTMLStencilElement {
    }
    var HTMLCBoxElement: {
        prototype: HTMLCBoxElement;
        new (): HTMLCBoxElement;
    };
    interface HTMLHBoxElement extends Components.HBox, HTMLStencilElement {
    }
    var HTMLHBoxElement: {
        prototype: HTMLHBoxElement;
        new (): HTMLHBoxElement;
    };
    interface HTMLVBoxElement extends Components.VBox, HTMLStencilElement {
    }
    var HTMLVBoxElement: {
        prototype: HTMLVBoxElement;
        new (): HTMLVBoxElement;
    };
    interface HTMLElementTagNameMap {
        "c-box": HTMLCBoxElement;
        "h-box": HTMLHBoxElement;
        "v-box": HTMLVBoxElement;
    }
}
declare namespace LocalJSX {
    interface CBox {
    }
    interface HBox {
        "bottom"?: boolean;
        "fill"?: boolean;
        "spread"?: boolean;
        "top"?: boolean;
        "wrap"?: boolean;
    }
    interface VBox {
    }
    interface IntrinsicElements {
        "c-box": CBox;
        "h-box": HBox;
        "v-box": VBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "c-box": LocalJSX.CBox & JSXBase.HTMLAttributes<HTMLCBoxElement>;
            "h-box": LocalJSX.HBox & JSXBase.HTMLAttributes<HTMLHBoxElement>;
            "v-box": LocalJSX.VBox & JSXBase.HTMLAttributes<HTMLVBoxElement>;
        }
    }
}
